"""Generate the hikes.walks seed migration from the legacy walks.db.

Reads the SQLite corpus checked into projects/hikes/scrape_walkhighlands/
walks.db and emits batched multi-row INSERT statements for the hikes.walks
Postgres table (Task 2 of the hikes-into-monolith plan). Stdlib only; run
with plain python3, no Bazel or third-party deps needed.

The stale viable_dates column in walks.db is deliberately ignored: the
forecast job recomputes windows from met.no after deploy.

Usage:
    python3 generate_seed.py [--db PATH] [--out PATH]

Writes the SQL to stdout when --out is omitted. Output is deterministic
(rows ordered by uuid) so regenerating from the same walks.db is a no-op
diff. Rows with NULL in any NOT NULL column are skipped with a stderr log.
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

COLUMNS = (
    "uuid",
    "name",
    "url",
    "distance_km",
    "ascent_m",
    "duration_h",
    "summary",
    "latitude",
    "longitude",
)

TEXT_COLUMNS = {"uuid", "name", "url", "summary"}
INT_COLUMNS = {"ascent_m"}

BATCH_SIZE = 200

HEADER = """\
-- hikes.walks seed data: the legacy WalkHighlands corpus.
--
-- Generated by projects/monolith/hikes/tools/generate_seed.py from the
-- SQLite database at projects/hikes/scrape_walkhighlands/walks.db.
-- Do not edit by hand; rerun the generator instead.
"""


def sql_literal(column: str, value: object) -> str:
    """Render a Python value as a Postgres literal for the given column."""
    if column in TEXT_COLUMNS:
        escaped = str(value).replace("'", "''")
        return f"'{escaped}'"
    if column in INT_COLUMNS:
        return str(int(value))
    # Floats: repr() is the shortest round-trip representation.
    return repr(float(value))


def generate(db_path: Path, out) -> tuple[int, int]:
    """Write the seed SQL to out; return (emitted, skipped) row counts."""
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        rows = conn.execute(
            f"SELECT {', '.join(COLUMNS)} FROM walks ORDER BY uuid"
        ).fetchall()
    finally:
        conn.close()

    kept: list[str] = []
    skipped = 0
    for row in rows:
        record = dict(zip(COLUMNS, row))
        # summary is NOT NULL DEFAULT '' in the schema, so a NULL summary is a
        # valid walk: coerce it rather than dropping the whole row.
        if record["summary"] is None:
            record["summary"] = ""
        if any(value is None for value in record.values()):
            skipped += 1
            print(f"skipping row with NULL column: uuid={row[0]!r}", file=sys.stderr)
            continue
        values = ", ".join(sql_literal(column, record[column]) for column in COLUMNS)
        kept.append(f"({values})")

    out.write(HEADER)
    for start in range(0, len(kept), BATCH_SIZE):
        batch = kept[start : start + BATCH_SIZE]
        out.write(f"\nINSERT INTO hikes.walks ({', '.join(COLUMNS)}) VALUES\n")
        out.write(",\n".join(batch))
        out.write("\nON CONFLICT (uuid) DO NOTHING;\n")

    return len(kept), skipped


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--db",
        type=Path,
        default=Path("projects/hikes/scrape_walkhighlands/walks.db"),
        help="path to the legacy SQLite database",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="output SQL path (defaults to stdout)",
    )
    args = parser.parse_args()

    if args.out is None:
        emitted, skipped = generate(args.db, sys.stdout)
    else:
        with args.out.open("w", encoding="utf-8") as handle:
            emitted, skipped = generate(args.db, handle)

    print(f"emitted {emitted} rows, skipped {skipped}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
