# Override BUILD for ambient-context (installed by extension.bzl).
# Why an override: the dune tree centers on a virtual library
# (ambient-context, virtual module ambient_context) with
# (default_implementation ambient-context.unix), a (select ...) clause for
# hmap, and a vendored Atomic compat module generated by a bundled gen.exe,
# none of which dune2bazel models. Per the plan's virtual-library dispatch,
# the override builds the concrete implementation Semgrep selects: the unix
# default, compiled together with the virtual module's interface as one
# library. hmap is in the lock, so the select resolves to the real
# implementation; on the pinned 5.3 sysroot gen.exe always emits
# `include Stdlib.Atomic` + atomic.post412.mli, replicated as genrules.
#
# The lock's url/sha256 pin deviates from opam-repository metadata: opam
# records only md5/sha512 for ambient-context 0.1.0 and GitHub has since
# regenerated the v0.1.0 tag tarball, so the recorded sha512 no longer
# matches any fetchable artifact. The entry pins the sha256 of the current
# tag tarball (tree verified against the v0.1.0 tag) and is marked
# "opam": false so --verify skips the metadata comparison.
#
# ambient-context-eio is not built: Semgrep's telemetry uses the
# opentelemetry fork's own ambient-context.eio storage instead.
load("@homelab//bazel/ocaml:defs.bzl", "ocaml_library")

genrule(
    name = "atomic_ml",
    outs = ["atomic.ml"],
    cmd = "printf 'include Stdlib.Atomic' > $@",
)

genrule(
    name = "atomic_mli",
    srcs = ["vendor/atomic/atomic.post412.mli"],
    outs = ["atomic.mli"],
    cmd = "cp $< $@",
)

# findlib ambient-context.atomic (vendored Atomic compat).
ocaml_library(
    name = "ambient_context_atomic",
    srcs = [
        ":atomic_ml",
        ":atomic_mli",
    ],
    visibility = ["//visibility:public"],
    wrapped = True,
)

# findlib ambient-context.thread_local (vendored TLS, extracted upstream
# from ocaml-opentelemetry).
ocaml_library(
    name = "ambient_context_thread_local",
    srcs = [
        "vendor/thread_local/thread_local.ml",
        "vendor/thread_local/thread_local.mli",
    ],
    opam_deps = ["threads"],
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = [":ambient_context_atomic"],
)

# The (select ambient_context_hmap.ml ...) clause: hmap is locked, so the
# real implementation wins over the vendored fallback.
genrule(
    name = "ambient_context_hmap_ml",
    srcs = ["lib/core/ambient_context_hmap.real.ml"],
    outs = ["ambient_context_hmap.ml"],
    cmd = "cp $< $@",
)

# findlib ambient-context.core.
ocaml_library(
    name = "ambient_context_core",
    srcs = [
        "lib/core/types.ml",
        "lib/core/types.mli",
        ":ambient_context_hmap_ml",
    ],
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = ["@ocaml_hmap//:hmap"],
)

# findlib ambient-context.tls (thread-local storage backend).
ocaml_library(
    name = "ambient_context_tls",
    srcs = ["lib/unix/tls/ambient_context_tls.ml"],
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = [
        ":ambient_context_core",
        ":ambient_context_thread_local",
    ],
)

# findlib ambient-context: the virtual module's interface (lib/) compiled
# with the unix default implementation (lib/unix/), as one concrete library.
ocaml_library(
    name = "ambient_context",
    srcs = [
        "lib/ambient_context.mli",
        "lib/unix/ambient_context.ml",
    ],
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = [
        ":ambient_context_atomic",
        ":ambient_context_core",
        ":ambient_context_thread_local",
        ":ambient_context_tls",
    ],
)

# findlib ambient-context-lwt (Lwt sequence-associated storage backend).
ocaml_library(
    name = "ambient_context_lwt",
    srcs = ["lib/lwt/ambient_context_lwt.ml"],
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = [
        ":ambient_context",
        ":ambient_context_tls",
        "@ocaml_lwt//:lwt",
    ],
)
