apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monolith
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: ghcr.io/jomcgi/homelab/charts
      chart: monolith
      targetRevision: 0.395.3
      helm:
        releaseName: monolith
        valueFiles:
          - $values/projects/monolith/deploy/values.yaml
          - $values/projects/monolith/deploy/values-gke.yaml
        ignoreMissingValueFiles: true
    - repoURL: https://github.com/jomcgi-org/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monolith
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
