# Override BUILD for ocplib-endian (installed by bazel/ocaml/opam/extension.bzl).
#
# Why an override: every module is generated by cppo (rule) stanzas whose
# inputs #include sibling fragment files (common.ml, be/le/ne_ocaml_401.ml).
# Those fragments are cppo inputs, NOT library modules; dune filters them out
# with (modules ...), which our rules do not model, so the generation is
# spelled out as genrules (the yojson override pattern) and each library
# compiles exactly its generated module set.
#
# The -V OCAML version pin: upstream passes -V OCAML:%{ocaml_version}; every
# conditional in this package discriminates OCaml 4.0x compatibility, so any
# 5.x value selects the modern branch. Revisit when the sysroot pin moves.
load("@homelab//bazel/ocaml:defs.bzl", "ocaml_library")

_CPPO = "@ocaml_cppo//:cppo"

# common_401.ml is itself generated, then #included by the endian* modules.
genrule(
    name = "common_401_ml",
    srcs = [
        "src/common_401.cppo.ml",
        "src/be_ocaml_401.ml",
        "src/le_ocaml_401.ml",
        "src/ne_ocaml_401.ml",
        "src/common_float.ml",
    ],
    outs = ["common_401.ml"],
    cmd = "W=$$(mktemp -d) && CP=$$(realpath $(location %s)) && " % _CPPO +
          "for f in $(SRCS); do cp $$f $$W/; done && " +
          "(cd $$W && $$CP -V OCAML:5.3.0 common_401.cppo.ml -o common_401.ml) && " +
          "cp $$W/common_401.ml $@",
    tools = [_CPPO],
)

# One genrule per generated module file. The .ml variants #include common.ml
# and the generated common_401.ml; the .mli variants are standalone.
[
    genrule(
        name = "gen_%s_ml" % mod,
        srcs = [
            "src/%s.cppo.ml" % mod,
            "src/common.ml",
            ":common_401_ml",
        ],
        outs = ["%s.ml" % mod],
        cmd = "W=$$(mktemp -d) && CP=$$(realpath $(location %s)) && " % _CPPO +
              "for f in $(SRCS); do cp $$f $$W/; done && " +
              ("(cd $$W && $$CP -V OCAML:5.3.0 {m}.cppo.ml -o {m}.ml) && " +
               "cp $$W/{m}.ml $@").format(m = mod),
        tools = [_CPPO],
    )
    for mod in [
        "endianString",
        "endianBytes",
        "endianBigstring",
    ]
]

[
    genrule(
        name = "gen_%s_mli" % mod,
        srcs = ["src/%s.cppo.mli" % mod],
        outs = ["%s.mli" % mod],
        cmd = "W=$$(mktemp -d) && CP=$$(realpath $(location %s)) && " % _CPPO +
              "for f in $(SRCS); do cp $$f $$W/; done && " +
              ("(cd $$W && $$CP -V OCAML:5.3.0 {m}.cppo.mli -o {m}.mli) && " +
               "cp $$W/{m}.mli $@").format(m = mod),
        tools = [_CPPO],
    )
    for mod in [
        "endianString",
        "endianBytes",
        "endianBigstring",
    ]
]

# findlib ocplib-endian: EndianString + EndianBytes (unwrapped).
ocaml_library(
    name = "ocplib_endian",
    srcs = [
        ":gen_endianBytes_ml",
        ":gen_endianBytes_mli",
        ":gen_endianString_ml",
        ":gen_endianString_mli",
    ],
    ocamlopt_flags = ["-inline", "1000"],
    visibility = ["//visibility:public"],
)

# findlib ocplib-endian.bigstring: EndianBigstring (Bigarray is stdlib at 5.x).
ocaml_library(
    name = "ocplib_endian_bigstring",
    srcs = [
        ":gen_endianBigstring_ml",
        ":gen_endianBigstring_mli",
    ],
    ocamlopt_flags = ["-inline", "1000"],
    visibility = ["//visibility:public"],
    deps = [":ocplib_endian"],
)
