"""k3s_archive - vendor the k3s binary plus its airgap image tarball per arch.

The EmberVM composite (R5) k3s guest images run a fully airgapped cluster: the
apko rootfs bakes both the static `k3s` binary and the matching
`k3s-airgap-images-<arch>.tar.zst`, so cluster bring-up pulls NOTHING from any
registry (standing decision 12). This repo rule downloads, per arch:

  - the k3s binary, placed at `/usr/local/bin/k3s` (mode 0755); and
  - the airgap image tarball, placed at
    `/var/lib/rancher/k3s/agent/images/k3s-airgap-images-<arch>.tar.zst`, where
    k3s auto-imports every archive at startup (compressed `.tar.zst` is imported
    directly, no decompression step in the guest).

It emits a small per-arch tar layer (`:tar_amd64` / `:tar_arm64`) the apko_image
consumes via `multiarch_tars`, mirroring kata_firecracker_archive: apko appends
`_amd64` / `_arm64` to the base label, so the images reference `@k3s_archive//:tar`.

Unlike kata_firecracker_archive this does NOT extract: both artifacts are opaque
files baked verbatim (the binary is an ELF, the tarball is imported intact by
k3s), so `repository_ctx.download` (not download_and_extract) fetches each.

The amd64 and arm64 k3s binaries have DIFFERENT release asset names (`k3s` vs
`k3s-arm64`); both land at the same in-image path `/usr/local/bin/k3s`, so the
per-arch rootfs is byte-for-byte the upstream binary for that arch.
"""

# In-image destination paths (identical across arches; the per-arch asset name
# difference is resolved at download time, not in the image layout).
_BINARY_DEST = "usr/local/bin/k3s"
_AIRGAP_DIR = "var/lib/rancher/k3s/agent/images"

def _k3s_archive_impl(repository_ctx):
    build_content = "# Generated by k3s_archive\n"

    for arch, bin_url, bin_sha, air_url, air_sha, air_name in [
        (
            "amd64",
            repository_ctx.attr.amd64_binary_url,
            repository_ctx.attr.amd64_binary_sha256,
            repository_ctx.attr.amd64_airgap_url,
            repository_ctx.attr.amd64_airgap_sha256,
            "k3s-airgap-images-amd64.tar.zst",
        ),
        (
            "arm64",
            repository_ctx.attr.arm64_binary_url,
            repository_ctx.attr.arm64_binary_sha256,
            repository_ctx.attr.arm64_airgap_url,
            repository_ctx.attr.arm64_airgap_sha256,
            "k3s-airgap-images-arm64.tar.zst",
        ),
    ]:
        if not bin_url:
            continue

        bin_file = arch + "_k3s"
        air_file = arch + "_" + air_name

        # download (not download_and_extract): both artifacts are baked verbatim.
        repository_ctx.download(url = bin_url, sha256 = bin_sha, output = bin_file, executable = True)
        repository_ctx.download(url = air_url, sha256 = air_sha, output = air_file)

        build_content += """
genrule(
    name = "tar_{arch}",
    srcs = ["{bin_file}", "{air_file}"],
    outs = ["tar_{arch}.tar"],
    cmd = '''
        mkdir -p tmp/{binary_dir} tmp/{airgap_dir}
        cp $(location {bin_file}) tmp/{binary_dest}
        cp $(location {air_file}) tmp/{airgap_dir}/{air_name}
        chmod 0755 tmp/{binary_dest}
        chmod 0644 tmp/{airgap_dir}/{air_name}
        tar -C tmp -cf $@ .
    ''',
    visibility = ["//visibility:public"],
)
""".format(
            arch = arch,
            bin_file = bin_file,
            air_file = air_file,
            binary_dir = _BINARY_DEST.rsplit("/", 1)[0],
            binary_dest = _BINARY_DEST,
            airgap_dir = _AIRGAP_DIR,
            air_name = air_name,
        )

    default_arch = "amd64" if repository_ctx.attr.amd64_binary_url else "arm64"

    # Convenience alias; apko_image's multiarch_tars appends _amd64/_arm64 to the
    # base label directly, so it targets :tar_amd64 / :tar_arm64 (not this alias).
    build_content += """
alias(
    name = "tar",
    actual = ":tar_{arch}",
    tags = ["multiarch_tar"],
    visibility = ["//visibility:public"],
)
""".format(arch = default_arch)

    repository_ctx.file("BUILD.bazel", build_content)

k3s_archive = repository_rule(
    implementation = _k3s_archive_impl,
    attrs = {
        "amd64_binary_url": attr.string(doc = "URL for the amd64 k3s binary"),
        "amd64_binary_sha256": attr.string(doc = "SHA256 of the amd64 k3s binary"),
        "amd64_airgap_url": attr.string(doc = "URL for the amd64 airgap images tarball (.tar.zst)"),
        "amd64_airgap_sha256": attr.string(doc = "SHA256 of the amd64 airgap tarball"),
        "arm64_binary_url": attr.string(doc = "URL for the arm64 k3s binary (asset name k3s-arm64)"),
        "arm64_binary_sha256": attr.string(doc = "SHA256 of the arm64 k3s binary"),
        "arm64_airgap_url": attr.string(doc = "URL for the arm64 airgap images tarball (.tar.zst)"),
        "arm64_airgap_sha256": attr.string(doc = "SHA256 of the arm64 airgap tarball"),
    },
    doc = """Download the k3s binary + its airgap image tarball per arch and emit a small
tar layer carrying `/usr/local/bin/k3s` and
`/var/lib/rancher/k3s/agent/images/k3s-airgap-images-<arch>.tar.zst`.

Usage in MODULE.bazel:

    k3s_archive = use_repo_rule("//bazel/tools/http:k3s_archive.bzl", "k3s_archive")
    k3s_archive(
        name = "k3s_archive",
        amd64_binary_url = "https://github.com/k3s-io/k3s/releases/download/v1.30.6+k3s1/k3s",
        amd64_binary_sha256 = "...",
        amd64_airgap_url = "https://github.com/k3s-io/k3s/releases/download/v1.30.6+k3s1/k3s-airgap-images-amd64.tar.zst",
        amd64_airgap_sha256 = "...",
        arm64_binary_url = "https://github.com/k3s-io/k3s/releases/download/v1.30.6+k3s1/k3s-arm64",
        arm64_binary_sha256 = "...",
        arm64_airgap_url = "https://github.com/k3s-io/k3s/releases/download/v1.30.6+k3s1/k3s-airgap-images-arm64.tar.zst",
        arm64_airgap_sha256 = "...",
    )

Then in an apko_image BUILD:

    apko_image(name = "image", multiarch_tars = ["@k3s_archive//:tar"])
""",
)
