"""kata_firecracker_archive - extract Firecracker tools + the guest kernel.

fc-invoke drives Firecracker directly and needs the `firecracker` hypervisor
binary, its `snapshot-editor`, and the matching guest kernel
(`vmlinux.container`). Baking those files into the fc-invoke image
removes the last node-level `/opt/kata` install step (see
projects/platform/firecracker-node), so a node only needs /dev/kvm and scratch.

The hypervisor binary and snapshot-editor come from the required upstream
Firecracker release configured by the `firecracker_*` attributes; only the
kernel comes from kata. The kata bundle pins a Firecracker several minor
versions behind upstream (v1.12.1
as of kata 3.32.0), which predates the vsock-after-snapshot-restore fixes the
EmberVM warm-restore fleet needs (#4389: upstream #5688 in v1.15.0, #5882 in
v1.16.0, #5958 in v1.16.1). Snapshot formats are version-locked and nothing
rebuilds existing snapshots automatically when this pin moves (the base
signature has no hypervisor input), so any version change here must move
hypervisorEpoch in projects/embervm/chart/values.yaml in the same PR
(//projects/embervm/chart:chart_hypervisor_epoch_test enforces it, #4409).

The per-arch kata-static bundle is large (~1.5 GiB amd64) and unpacks to several
GiB, but only the kernel plus the upstream Firecracker and snapshot-editor ride
into the image. The full extraction is deleted after the kernel is copied out,
so the external repo retains only the three artifacts rather than the whole
decompressed bundle. Bazel's built-in
`download_and_extract` handles the `.tar.zst` compression, so no `zstd` binary is
required on the fetch executor.
"""

# Member paths inside the kata-static tarball (entries are rooted at ./opt/kata).
# `vmlinux.container` is a symlink to the versioned kernel, so the copy below
# dereferences it (cp -L) to land the real kernel in the image.
_KERNEL_MEMBER = "opt/kata/share/kata-containers/vmlinux.container"

# Upstream Firecracker release tarballs name their arches x86_64/aarch64 rather
# than the amd64/arm64 the kata bundles (and our image rules) use.
_FC_RELEASE_ARCH = {
    "amd64": "x86_64",
    "arm64": "aarch64",
}

def _kata_firecracker_archive_impl(repository_ctx):
    package_dir = repository_ctx.attr.package_dir
    fc_version = repository_ctx.attr.firecracker_version
    if not fc_version and (repository_ctx.attr.amd64_firecracker_url or repository_ctx.attr.arm64_firecracker_url):
        fail("kata_firecracker_archive: firecracker_version is required when a firecracker_url override is set (it names the members inside the release tarball)")

    build_content = "# Generated by kata_firecracker_archive\n"

    for arch, url, sha, fc_url, fc_sha in [
        (
            "amd64",
            repository_ctx.attr.amd64_url,
            repository_ctx.attr.amd64_sha256,
            repository_ctx.attr.amd64_firecracker_url,
            repository_ctx.attr.amd64_firecracker_sha256,
        ),
        (
            "arm64",
            repository_ctx.attr.arm64_url,
            repository_ctx.attr.arm64_sha256,
            repository_ctx.attr.arm64_firecracker_url,
            repository_ctx.attr.arm64_firecracker_sha256,
        ),
    ]:
        if not url:
            continue
        if not fc_url:
            fail("kata_firecracker_archive: an upstream firecracker_url is required so firecracker and snapshot-editor come from the same release")

        extracted = arch + "_extracted"
        repository_ctx.download_and_extract(
            url = url,
            sha256 = sha,
            output = extracted,
            type = "tar.zst",
        )

        # cp -L dereferences vmlinux.container, a symlink to the versioned kernel.
        repository_ctx.execute(["cp", "-L", extracted + "/" + _KERNEL_MEMBER, arch + "_vmlinux.container"])

        # Reclaim the multi-GiB decompressed bundle; only the needed files survive.
        repository_ctx.delete(extracted)

        # Upstream release tarball layout:
        #   release-v<ver>-<fcarch>/firecracker-v<ver>-<fcarch>
        fc_arch = _FC_RELEASE_ARCH[arch]
        fc_extracted = arch + "_fc_extracted"
        repository_ctx.download_and_extract(
            url = fc_url,
            sha256 = fc_sha,
            output = fc_extracted,
            type = "tgz",
        )
        release_dir = "release-{v}-{a}".format(v = fc_version, a = fc_arch)
        fc_member = release_dir + "/firecracker-{v}-{a}".format(v = fc_version, a = fc_arch)
        editor_member = release_dir + "/snapshot-editor-{v}-{a}".format(v = fc_version, a = fc_arch)
        result = repository_ctx.execute(["cp", "-L", fc_extracted + "/" + fc_member, arch + "_firecracker"])
        if result.return_code != 0:
            fail("kata_firecracker_archive: firecracker member %s not found in %s: %s" % (fc_member, fc_url, result.stderr))
        result = repository_ctx.execute(["cp", "-L", fc_extracted + "/" + editor_member, arch + "_snapshot-editor"])
        if result.return_code != 0:
            fail("kata_firecracker_archive: snapshot-editor member %s not found in %s: %s" % (editor_member, fc_url, result.stderr))
        repository_ctx.delete(fc_extracted)

        repository_ctx.execute(["chmod", "0755", arch + "_firecracker"])
        repository_ctx.execute(["chmod", "0755", arch + "_snapshot-editor"])
        repository_ctx.execute(["chmod", "0644", arch + "_vmlinux.container"])

        build_content += """
genrule(
    name = "tar_{arch}",
    srcs = ["{arch}_firecracker", "{arch}_snapshot-editor", "{arch}_vmlinux.container"],
    outs = ["tar_{arch}.tar"],
    cmd = '''
        mkdir -p tmp{package_dir}
        cp $(location {arch}_firecracker) tmp{package_dir}/firecracker
        cp $(location {arch}_snapshot-editor) tmp{package_dir}/snapshot-editor
        cp $(location {arch}_vmlinux.container) tmp{package_dir}/vmlinux.container
        chmod 0755 tmp{package_dir}/firecracker
        chmod 0755 tmp{package_dir}/snapshot-editor
        chmod 0644 tmp{package_dir}/vmlinux.container
        tar -C tmp -czf $@ .
    ''',
    visibility = ["//visibility:public"],
)
""".format(arch = arch, package_dir = package_dir)

    default_arch = "amd64" if repository_ctx.attr.amd64_url else "arm64"

    # Convenience alias; apko_image's multiarch_tars appends _amd64/_arm64 to the
    # base label directly, so it targets :tar_amd64 / :tar_arm64 (not this alias).
    build_content += """
alias(
    name = "tar",
    actual = ":tar_{arch}",
    tags = ["multiarch_tar"],
    visibility = ["//visibility:public"],
)
""".format(arch = default_arch)

    repository_ctx.file("BUILD.bazel", build_content)

kata_firecracker_archive = repository_rule(
    implementation = _kata_firecracker_archive_impl,
    attrs = {
        "amd64_url": attr.string(doc = "URL for the amd64 kata-static .tar.zst bundle"),
        "amd64_sha256": attr.string(doc = "SHA256 of the amd64 bundle"),
        "arm64_url": attr.string(doc = "URL for the arm64 kata-static .tar.zst bundle"),
        "arm64_sha256": attr.string(doc = "SHA256 of the arm64 bundle"),
        "firecracker_version": attr.string(
            doc = "Upstream Firecracker release tag (e.g. v1.16.1); required when any firecracker_url override is set",
        ),
        "amd64_firecracker_url": attr.string(
            doc = "Required upstream firecracker release .tgz for amd64 (kernel still comes from kata)",
        ),
        "amd64_firecracker_sha256": attr.string(doc = "SHA256 of the amd64 firecracker release .tgz"),
        "arm64_firecracker_url": attr.string(
            doc = "Required upstream firecracker release .tgz for arm64 (kernel still comes from kata)",
        ),
        "arm64_firecracker_sha256": attr.string(doc = "SHA256 of the arm64 firecracker release .tgz"),
        "package_dir": attr.string(
            default = "/opt/fc",
            doc = "Directory the firecracker binary, snapshot-editor, and kernel are placed in inside the image",
        ),
    },
    doc = """Download a kata-containers static bundle per arch and emit a small tar layer
carrying `firecracker`, `snapshot-editor`, and `vmlinux.container` at `package_dir`.

Usage in MODULE.bazel:

    kata_firecracker_archive = use_repo_rule("//bazel/tools/http:kata_firecracker_archive.bzl", "kata_firecracker_archive")
    kata_firecracker_archive(
        name = "kata_firecracker",
        amd64_url = "https://github.com/kata-containers/kata-containers/releases/download/3.32.0/kata-static-3.32.0-amd64.tar.zst",
        amd64_sha256 = "...",
        arm64_url = "https://github.com/kata-containers/kata-containers/releases/download/3.32.0/kata-static-3.32.0-arm64.tar.zst",
        arm64_sha256 = "...",
    )

Then in an apko_image BUILD:

    apko_image(name = "image", multiarch_tars = ["@kata_firecracker//:tar"])
""",
)
