"""kata_firecracker_archive - extract firecracker + the guest kernel from a kata-containers static bundle.

fc-invoke drives Firecracker directly and needs exactly two files from kata's
static release: the `firecracker` hypervisor binary and the matching guest
kernel (`vmlinux.container`). Baking those two files into the fc-invoke image
removes the last node-level `/opt/kata` install step (see
projects/platform/firecracker-node), so a node only needs /dev/kvm and scratch.

The per-arch kata-static bundle is large (~1.5 GiB amd64) and unpacks to several
GiB, but only these two files ride into the image (~45 MiB). The full extraction
is deleted after the two files are copied out, so the external repo retains only
the two artifacts rather than the whole decompressed bundle. Bazel's built-in
`download_and_extract` handles the `.tar.zst` compression, so no `zstd` binary is
required on the fetch executor.
"""

# Member paths inside the kata-static tarball (entries are rooted at ./opt/kata).
# `vmlinux.container` is a symlink to the versioned kernel, so the copy below
# dereferences it (cp -L) to land the real kernel in the image.
_FIRECRACKER_MEMBER = "opt/kata/bin/firecracker"
_KERNEL_MEMBER = "opt/kata/share/kata-containers/vmlinux.container"

def _kata_firecracker_archive_impl(repository_ctx):
    package_dir = repository_ctx.attr.package_dir

    build_content = "# Generated by kata_firecracker_archive\n"

    for arch, url, sha in [
        ("amd64", repository_ctx.attr.amd64_url, repository_ctx.attr.amd64_sha256),
        ("arm64", repository_ctx.attr.arm64_url, repository_ctx.attr.arm64_sha256),
    ]:
        if not url:
            continue

        extracted = arch + "_extracted"
        repository_ctx.download_and_extract(
            url = url,
            sha256 = sha,
            output = extracted,
            type = "tar.zst",
        )

        # cp -L dereferences: firecracker is a regular ELF, vmlinux.container is
        # a symlink to the versioned kernel; both land as real files.
        repository_ctx.execute(["cp", "-L", extracted + "/" + _FIRECRACKER_MEMBER, arch + "_firecracker"])
        repository_ctx.execute(["cp", "-L", extracted + "/" + _KERNEL_MEMBER, arch + "_vmlinux.container"])
        repository_ctx.execute(["chmod", "0755", arch + "_firecracker"])
        repository_ctx.execute(["chmod", "0644", arch + "_vmlinux.container"])

        # Reclaim the multi-GiB decompressed bundle; only the two files survive.
        repository_ctx.delete(extracted)

        build_content += """
genrule(
    name = "tar_{arch}",
    srcs = ["{arch}_firecracker", "{arch}_vmlinux.container"],
    outs = ["tar_{arch}.tar"],
    cmd = '''
        mkdir -p tmp{package_dir}
        cp $(location {arch}_firecracker) tmp{package_dir}/firecracker
        cp $(location {arch}_vmlinux.container) tmp{package_dir}/vmlinux.container
        chmod 0755 tmp{package_dir}/firecracker
        chmod 0644 tmp{package_dir}/vmlinux.container
        tar -C tmp -czf $@ .
    ''',
    visibility = ["//visibility:public"],
)
""".format(arch = arch, package_dir = package_dir)

    default_arch = "amd64" if repository_ctx.attr.amd64_url else "arm64"

    # Convenience alias; apko_image's multiarch_tars appends _amd64/_arm64 to the
    # base label directly, so it targets :tar_amd64 / :tar_arm64 (not this alias).
    build_content += """
alias(
    name = "tar",
    actual = ":tar_{arch}",
    tags = ["multiarch_tar"],
    visibility = ["//visibility:public"],
)
""".format(arch = default_arch)

    repository_ctx.file("BUILD.bazel", build_content)

kata_firecracker_archive = repository_rule(
    implementation = _kata_firecracker_archive_impl,
    attrs = {
        "amd64_url": attr.string(doc = "URL for the amd64 kata-static .tar.zst bundle"),
        "amd64_sha256": attr.string(doc = "SHA256 of the amd64 bundle"),
        "arm64_url": attr.string(doc = "URL for the arm64 kata-static .tar.zst bundle"),
        "arm64_sha256": attr.string(doc = "SHA256 of the arm64 bundle"),
        "package_dir": attr.string(
            default = "/opt/fc",
            doc = "Directory the firecracker binary + kernel are placed in inside the image",
        ),
    },
    doc = """Download a kata-containers static bundle per arch and emit a small tar layer
carrying just `firecracker` and `vmlinux.container` at `package_dir`.

Usage in MODULE.bazel:

    kata_firecracker_archive = use_repo_rule("//bazel/tools/http:kata_firecracker_archive.bzl", "kata_firecracker_archive")
    kata_firecracker_archive(
        name = "kata_firecracker",
        amd64_url = "https://github.com/kata-containers/kata-containers/releases/download/3.32.0/kata-static-3.32.0-amd64.tar.zst",
        amd64_sha256 = "...",
        arm64_url = "https://github.com/kata-containers/kata-containers/releases/download/3.32.0/kata-static-3.32.0-arm64.tar.zst",
        arm64_sha256 = "...",
    )

Then in an apko_image BUILD:

    apko_image(name = "image", multiarch_tars = ["@kata_firecracker//:tar"])
""",
)
