"""multiarch_http_file - Download and package multiarch binaries from HTTP"""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

def _multiarch_http_file_impl(repository_ctx):
    """Implementation for multiarch_http_file repository rule."""

    # Create BUILD file that exposes the binaries and tars
    build_content = """# Generated by multiarch_http_file
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")

"""

    # Add filegroups for the downloaded binaries
    if repository_ctx.attr.amd64_url:
        build_content += """
filegroup(
    name = "amd64",
    srcs = ["amd64_binary"],
    visibility = ["//visibility:public"],
)

"""

    if repository_ctx.attr.arm64_url:
        build_content += """
filegroup(
    name = "arm64",
    srcs = ["arm64_binary"],
    visibility = ["//visibility:public"],
)

"""

    # Add platform-specific tars
    binary_name = repository_ctx.attr.binary_name
    package_dir = repository_ctx.attr.package_dir
    repo_name = repository_ctx.name

    # Extra archive paths (dirs or files) shipped beside the binary. Each is
    # symlinked into the repo as <arch>_extra_<i> and copied into package_dir
    # under its basename, so a release whose binary loads assets relative to
    # argv0 (e.g. pi's theme/ JSONs) works from the image.
    extras = repository_ctx.attr.extract_extra_paths

    def _extra_srcs(arch):
        return "".join([', "%s_extra_%d"' % (arch, i) for i in range(len(extras))])

    def _extra_cmds(arch):
        lines = []
        for i, path in enumerate(extras):
            base = path.rstrip("/").split("/")[-1]
            lines.append("        cp -LR $(location :%s_extra_%d) tmp/%s/%s" % (arch, i, package_dir, base))
        return "\n".join(lines)

    if repository_ctx.attr.amd64_url:
        build_content += """
# Create tar directly with genrule to control the exact structure
genrule(
    name = "tar_amd64",
    srcs = ["amd64_binary"{extra_srcs}],
    outs = ["tar_amd64.tar"],
    cmd = '''
        mkdir -p tmp/{package_dir}
        cp $(location :amd64_binary) tmp/{package_dir}/{binary_name}
        chmod 0755 tmp/{package_dir}/{binary_name}
{extra_cmds}
        tar -C tmp -czf $@ .
    ''',
    visibility = ["//visibility:public"],
)

""".format(package_dir = package_dir, binary_name = binary_name, extra_srcs = _extra_srcs("amd64"), extra_cmds = _extra_cmds("amd64"))

    if repository_ctx.attr.arm64_url:
        build_content += """
# Create tar directly with genrule to control the exact structure
genrule(
    name = "tar_arm64",
    srcs = ["arm64_binary"{extra_srcs}],
    outs = ["tar_arm64.tar"],
    cmd = '''
        mkdir -p tmp/{package_dir}
        cp $(location :arm64_binary) tmp/{package_dir}/{binary_name}
        chmod 0755 tmp/{package_dir}/{binary_name}
{extra_cmds}
        tar -C tmp -czf $@ .
    ''',
    visibility = ["//visibility:public"],
)

""".format(package_dir = package_dir, binary_name = binary_name, extra_srcs = _extra_srcs("arm64"), extra_cmds = _extra_cmds("arm64"))

    # Add alias for the main target
    if repository_ctx.attr.amd64_url:
        actual = "amd64"
    else:
        actual = "arm64"

    build_content += """
# Main target (alias to amd64 if available, otherwise arm64)
alias(
    name = "binary",
    actual = ":{actual}",
    visibility = ["//visibility:public"],
)

# Tar alias for use with multiarch_tars parameter
alias(
    name = "tar",
    actual = ":tar_{actual}",
    tags = ["multiarch_tar"],
    visibility = ["//visibility:public"],
)
""".format(actual = actual)

    repository_ctx.file("BUILD.bazel", build_content)

    # Download the binaries. With extract_path set the URL is an archive
    # (e.g. a GitHub release .tar.gz); it is extracted and the binary at
    # extract_path inside it becomes the per-arch binary. Without it the URL
    # is the raw binary, downloaded directly (the original behavior).
    extract_path = repository_ctx.attr.extract_path

    if repository_ctx.attr.amd64_url:
        if extract_path:
            repository_ctx.download_and_extract(
                url = repository_ctx.attr.amd64_url,
                output = "amd64_extract",
                sha256 = repository_ctx.attr.amd64_sha256,
            )
            repository_ctx.symlink("amd64_extract/" + extract_path, "amd64_binary")
            for i, extra in enumerate(repository_ctx.attr.extract_extra_paths):
                repository_ctx.symlink("amd64_extract/" + extra.rstrip("/"), "amd64_extra_%d" % i)
        else:
            repository_ctx.download(
                url = repository_ctx.attr.amd64_url,
                output = "amd64_binary",
                sha256 = repository_ctx.attr.amd64_sha256,
                executable = True,
            )

    if repository_ctx.attr.arm64_url:
        if extract_path:
            repository_ctx.download_and_extract(
                url = repository_ctx.attr.arm64_url,
                output = "arm64_extract",
                sha256 = repository_ctx.attr.arm64_sha256,
            )
            repository_ctx.symlink("arm64_extract/" + extract_path, "arm64_binary")
            for i, extra in enumerate(repository_ctx.attr.extract_extra_paths):
                repository_ctx.symlink("arm64_extract/" + extra.rstrip("/"), "arm64_extra_%d" % i)
        else:
            repository_ctx.download(
                url = repository_ctx.attr.arm64_url,
                output = "arm64_binary",
                sha256 = repository_ctx.attr.arm64_sha256,
                executable = True,
            )

multiarch_http_file = repository_rule(
    implementation = _multiarch_http_file_impl,
    attrs = {
        "amd64_url": attr.string(
            doc = "URL for amd64 binary",
        ),
        "amd64_sha256": attr.string(
            doc = "SHA256 checksum for amd64 binary",
        ),
        "arm64_url": attr.string(
            doc = "URL for arm64 binary",
        ),
        "arm64_sha256": attr.string(
            doc = "SHA256 checksum for arm64 binary",
        ),
        "binary_name": attr.string(
            mandatory = True,
            doc = "Name of the binary in the tar (e.g., 'ttyd')",
        ),
        "package_dir": attr.string(
            default = "/usr/local/bin",
            doc = "Directory to place the binary in the image",
        ),
        "extract_extra_paths": attr.string_list(
            doc = "Archive-relative paths (dirs or files) copied into " +
                  "package_dir beside the binary, each under its basename. " +
                  "Only meaningful with extract_path.",
        ),
        "extract_path": attr.string(
            doc = "When set, the URLs are archives; extract and use the file at " +
                  "this path inside the archive as the binary (e.g. 'k9s' for a " +
                  "GitHub release tar.gz with the binary at its root).",
        ),
    },
    doc = """Download multiarch binaries from HTTP and create platform-specific tars.

This is a repository rule that downloads binaries for multiple architectures
and creates both the raw binaries and platform-specific tars in one go.

Example usage in MODULE.bazel:

    load("//bazel/tools/http:multiarch_http_file.bzl", "multiarch_http_file")

    multiarch_http_file(
        name = "ttyd",
        amd64_url = "https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.x86_64",
        amd64_sha256 = "...",
        arm64_url = "https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.aarch64",
        arm64_sha256 = "...",
        binary_name = "ttyd",
    )

Then in BUILD files:

    apko_image(
        name = "my_image",
        multiarch_tars = ["@ttyd//:tar"],
    )

Or use the binary directly:

    sh_binary(
        name = "test",
        srcs = ["test.sh"],
        data = ["@ttyd//:binary"],
    )
""",
)
