# Override BUILD for menhir (installed by extension.bzl).
#
# Why an override: menhir is a parser generator that bootstraps itself. Its dune
# tree builds the tool in stages (stage1 generated by ocamlyacc, stage2 by
# stage1, stage3 for fixed-point grammar tables). We build only **stage1**: it
# uses ocamlyacc (which the sysroot ships) for its own bootstrap parser and
# produces a fully functional menhir binary; stages 2/3 only re-derive the tool
# from itself and are not needed to *use* menhir as a generator.
#
# The opam packages menhir / menhirLib / menhirSdk all ship from this one
# tarball; this override exposes the libraries plus the `menhir` binary that the
# `menhir` rule attribute consumes.
#
# Version-stamped sources (StaticVersion, version, profile) and the embedded
# standard library / packed menhirLib source are generated by genrules, mirroring
# the upstream dune rules.
load("@homelab//bazel/ocaml:defs.bzl", "ocaml_binary", "ocaml_library")

_VERSION = "20240715"

# --- runtime + sdk libraries --------------------------------------------------

genrule(
    name = "static_version",
    outs = [
        "StaticVersion.ml",
        "StaticVersion.mli",
    ],
    cmd = "printf 'let require_%s = ()\\n' > $(location StaticVersion.ml) && " % _VERSION +
          "printf 'val require_%s: unit\\n' > $(location StaticVersion.mli)" % _VERSION,
)

# menhirLib's installed form is the packed module MenhirLib.<Submodule>; a
# wrapped library over lib/*.{ml,mli} produces exactly that public API.
ocaml_library(
    name = "menhirLib",
    srcs = glob(["lib/*.ml", "lib/*.mli"]) + [
        "StaticVersion.ml",
        "StaticVersion.mli",
    ],
    wrapped = True,
    visibility = ["//visibility:public"],
)

genrule(
    name = "sdk_version",
    outs = ["version.ml"],
    cmd = "printf 'let version = \"%s\"\\n' > $@" % _VERSION,
)

ocaml_library(
    name = "menhirSdk",
    srcs = glob(["sdk/*.ml", "sdk/*.mli"]) + ["version.ml"],
    wrapped = True,
    visibility = ["//visibility:public"],
)

# menhirCST: runtime support for parsers generated with --cst. Built for
# completeness (a published menhir library); the binary does not link it.
ocaml_library(
    name = "menhirCST",
    srcs = [
        "cst/Settle.ml",
        "cst/Settle.mli",
    ],
    wrapped = True,
    visibility = ["//visibility:public"],
)

# --- vendored support libraries (renamed to avoid clashing with a system copy) -

ocaml_library(
    name = "vendored_fix",
    srcs = glob(["fix/src/*.ml", "fix/src/*.mli"]),
    wrapped = True,
)

ocaml_library(
    name = "vendored_pprint",
    srcs = glob(["pprint/src/*.ml", "pprint/src/*.mli"]),
    ocamlopt_flags = [
        "-w",
        "@A-4",
    ],
)

# --- stage1 generated sources -------------------------------------------------

# menhir embeds standard.mly (its parameterized-grammar prelude) as a string.
genrule(
    name = "standard_mly",
    srcs = ["src/standard.mly"],
    outs = ["standard_mly.ml"],
    cmd = "{ echo 'let contents = {|'; cat $(location src/standard.mly); echo '|}'; } > $@",
)

# menhir embeds the *packed* menhirLib source so it can emit self-contained
# parsers. pack.exe concatenates the modules named in menhirLib.mlpack; we run
# the upstream tool to stay faithful.
ocaml_binary(
    name = "pack",
    srcs = ["lib/pack/pack.ml"],
)

# The lib/ sources plus the generated StaticVersion -- the modules pack.exe
# concatenates. Collected as a filegroup so the genrule can stage them by
# basename into the layout pack.exe expects (menhirLib.mlpack in cwd, modules
# in the parent dir).
filegroup(
    name = "menhirlib_modules",
    srcs = glob(["lib/*.ml", "lib/*.mli"]) + [
        "StaticVersion.ml",
        "StaticVersion.mli",
    ],
)

genrule(
    name = "menhir_lib_source",
    srcs = [
        ":menhirlib_modules",
        "lib/pack/menhirLib.mlpack",
    ],
    outs = ["menhirLibSource.ml"],
    # pack.exe reads menhirLib.mlpack from cwd and ../<module>.{ml,mli}.
    cmd = "W=$$(mktemp -d) && mkdir $$W/pack && " +
          "cp $(locations :menhirlib_modules) $$W/ && " +
          "cp $(location lib/pack/menhirLib.mlpack) $$W/pack/ && " +
          "cp $(location :pack) $$W/pack/pack.exe && " +
          "(cd $$W/pack && ./pack.exe) && " +
          "{ echo 'let impl = {|'; cat $$W/pack/menhirLib.ml; echo '|}'; " +
          "  echo 'let intf = {|'; cat $$W/pack/menhirLib.mli; echo '|}'; } > $@",
    tools = [":pack"],
)

# profile.ml distinguishes dev vs release builds; we build as release.
genrule(
    name = "profile",
    outs = ["profile.ml"],
    cmd = "printf 'let release = true\\n' > $@",
)

# --- the menhir binary (stage1) ----------------------------------------------
# srcs: the engine (src/*.{ml,mli}), the lexers (.mll) and the sentence parser
# (.mly) which the driver runs through ocamllex/ocamlyacc, the StackLang
# modules, stage1's own bootstrap parser + Driver, and the generated embeds.
# standard.mly is excluded from srcs (it is embedded, not an ocamlyacc grammar).
ocaml_binary(
    name = "menhir",
    srcs = glob(
        [
            "src/*.ml",
            "src/*.mli",
            "src/*.mll",
            "src/StackLang/*.ml",
            "src/StackLang/*.mli",
        ],
    ) + [
        "src/sentenceParser.mly",
        "src/stage1/Driver.ml",
        "src/stage1/parser.mly",
        "standard_mly.ml",
        "menhirLibSource.ml",
        "profile.ml",
    ],
    # Version (MenhirSdk.Version) is opened so the engine sees it unqualified.
    ocamlopt_flags = [
        "-open",
        "MenhirSdk",
    ],
    opam_deps = ["unix"],
    deps = [
        ":menhirLib",
        ":menhirSdk",
        ":vendored_fix",
        ":vendored_pprint",
    ],
    visibility = ["//visibility:public"],
)
