{{- if or .Values.stars.s3SecretRefName .Values.stars.onepassword.itemPath }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "monolith.fullname" . }}-r2-s3
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monolith.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.stars.onepassword.itemPath | quote }}
{{- end }}
