{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fc-agentd.serviceAccountName" . }}
  labels:
    {{- include "fc-agentd.labels" . | nindent 4 }}
{{- end -}}
