load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

ts_project(
    name = "types",
    srcs = ["index.ts"],
    no_emit = True,
    preserve_jsx = False,
    tsconfig = "//projects/grimoire/frontend:tsconfig",
)
