# Override BUILD for base (installed by extension.bzl).
#
# Why an override: base's dune tree has codegen and a configurator probe the
# translator does not model. Each piece maps onto something we already have:
#
#   * random_repr.ml: upstream runs %{ocaml} over select-random-repr/select.ml
#     with the compiler version; the genrule below does exactly that against
#     the sysroot tar (the output discriminates only on OCaml >= 5.0, so it is
#     arch-independent and the unconstrained sysroot is correct).
#   * pow_overflow_bounds.ml: upstream generates it with a (mode fallback)
#     rule, and the release tarball ships the pre-generated file, so the
#     fallback applies and nothing runs.
#   * mpopcnt.sexp (discover.exe): probes whether the C compiler accepts
#     -mpopcnt, an x86-only codegen hint for hash_stubs. Pinned to no flag:
#     the portable fallback is correct on both arches (and arm64 has no
#     -mpopcnt at all). Likewise the ocamlopt-flags rule upstream pins to ().
#   * The stub (flags ... -D_LARGEFILE64_SOURCE) is dropped: no base stub
#     references any *64 symbol (grep open64/stat64/lseek64 comes up empty);
#     the define is a no-op here.
#   * shadow_stdlib.mli: generated by gen.exe (str + compiler-libs.common)
#     introspecting the sysroot's stdlib.cmi, the ocaml-compiler-libs
#     generator pattern.
#   * The (lint (pps ...)) field only runs under `dune lint`; inert.
#   * base_internalhash_types and shadow_stdlib are sublibraries of this same
#     tarball (hash_types/src, shadow-stdlib/src).
load("@homelab//bazel/ocaml:defs.bzl", "ocaml_binary", "ocaml_library")

_SYSROOT = "@homelab//bazel/ocaml/toolchain:ocaml_compiler"

ocaml_library(
    name = "base_internalhash_types",
    srcs = ["hash_types/src/base_internalhash_types.ml"],
    c_headers = ["hash_types/src/internalhash.h"],
    c_srcs = ["hash_types/src/internalhash_stubs.c"],
    visibility = ["//visibility:public"],
    wrapped = True,
)

# The shadow_stdlib interface is derived from the exact stdlib it shadows:
# gen.exe pretty-prints the sysroot's stdlib.cmi signature and rewrites every
# item into a deprecated alias.
ocaml_binary(
    name = "shadow_gen",
    srcs = [
        "shadow-stdlib/gen/gen.ml",
        "shadow-stdlib/gen/mapper.mll",
    ],
    opam_deps = [
        "str",
        "compiler-libs.common",
    ],
)

genrule(
    name = "shadow_stdlib_mli",
    srcs = [_SYSROOT],
    outs = ["shadow_stdlib.mli"],
    cmd = "T=$$(mktemp -d) && tar -xf $(location %s) -C $$T && " % _SYSROOT +
          "G=$$(realpath $(location :shadow_gen)) && " +
          "OCAMLLIB=$$T/lib/ocaml $$G -caml-cmi -permissive " +
          "$$T/lib/ocaml/stdlib.cmi $$T/lib/ocaml/stdlib.cma -o $@",
    tools = [":shadow_gen"],
)

ocaml_library(
    name = "shadow_stdlib",
    srcs = [
        "shadow-stdlib/src/shadow_stdlib.ml",
        ":shadow_stdlib_mli",
    ],
    visibility = ["//visibility:public"],
    wrapped = True,
)

# Upstream: (run %{ocaml} select.ml -ocaml-version %{ocaml_version} -o ...).
# The script branches only on the 5.0 floor, so the output is identical on
# both arches and the unconstrained sysroot is the right tool source.
genrule(
    name = "random_repr_ml",
    srcs = [
        "src/select-random-repr/select.ml",
        _SYSROOT,
    ],
    outs = ["random_repr.ml"],
    cmd = "T=$$(mktemp -d) && tar -xf $(location %s) -C $$T && " % _SYSROOT +
          "OCAMLLIB=$$T/lib/ocaml $$T/bin/ocaml " +
          "$(location src/select-random-repr/select.ml) " +
          "-ocaml-version 5.3 -o $@",
)

ocaml_library(
    name = "base",
    srcs = glob([
        "src/*.ml",
        "src/*.mli",
        "src/*.mll",
    ]) + [":random_repr_ml"],
    c_srcs = glob(["src/*.c"]),
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = [
        ":base_internalhash_types",
        ":shadow_stdlib",
        "@ocaml_ocaml_intrinsics_kernel//:ocaml_intrinsics_kernel",
        "@ocaml_sexplib0//:sexplib0",
    ],
)
