apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grimoire-oidc-client
  namespace: {{ .Release.Namespace }}
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/k8s-homelab/items/grimoire-oidc
