apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "git-mirror.fullname" . }}-mirrors
  labels:
    {{- include "git-mirror.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mirrors.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mirrors.size }}
