filegroup(
    name = "deploy_values",
    srcs = ["values.yaml"],
    visibility = [
        "//projects/monolith:__subpackages__",
        "//projects/monolith-public/chart:__pkg__",
    ],
)

filegroup(
    name = "gke_values",
    srcs = ["values-gke.yaml"],
    visibility = [
        "//projects/monolith:__subpackages__",
        "//projects/monolith-public/chart:__pkg__",
    ],
)
