defmodule Embervm.NodeAuthTest do
  @moduledoc """
  Pins the control-plane dial options. The plaintext bearer path (the default)
  must stay byte-for-byte what it was before the SPIFFE dial landed (#5758),
  and the mTLS path must read credentials from files at dial time, disable SNI,
  verify the peer chain against the bundle, and accept only the exact noded
  SPIFFE URI SAN. The handshake tests run a real `:ssl` listener on loopback
  with certificates generated by `:public_key.pkix_test_data/1`, so no fixture
  files and no network beyond 127.0.0.1.
  """
  use ExUnit.Case, async: false

  alias Embervm.NodeAuth

  @noded_id "spiffe://embervm.jomcgi.dev/ns/embervm/sa/embervm-embervm-noded"
  @control_plane_id "spiffe://embervm.jomcgi.dev/ns/embervm/sa/embervm-embervm"
  @plaintext_opts [adapter_opts: [transport_opts: [timeout: 3_000]]]
  # Explicit RSA keys: pkix_test_data's default picks the first curve in
  # crypto:ec_curves/0, and its EC peer certificates do not negotiate under
  # OTP 27's TLS 1.3 server (unable_to_supply_acceptable_cert). RSA is what
  # the test verifies, not what SPIRE issues; the verify_fun is key-agnostic.
  @key [key: {:rsa, 2048, 65_537}]

  setup do
    previous_token = Application.get_env(:embervm, :noded_bearer_token, :not_set)
    previous_tls = Application.get_env(:embervm, :noded_tls, :not_set)

    on_exit(fn ->
      restore(:noded_bearer_token, previous_token)
      restore(:noded_tls, previous_tls)
    end)

    Application.delete_env(:embervm, :noded_tls)
    :ok
  end

  defp restore(key, :not_set), do: Application.delete_env(:embervm, key)
  defp restore(key, value), do: Application.put_env(:embervm, key, value)

  describe "plaintext bearer dial (default, SPIFFE dial off)" do
    test "empty token attaches no connection header" do
      Application.put_env(:embervm, :noded_bearer_token, "  ")
      assert NodeAuth.connect_opts() == @plaintext_opts
    end

    test "configured token attaches a bearer authorization header" do
      Application.put_env(:embervm, :noded_bearer_token, "  node-secret\n")

      assert NodeAuth.connect_opts() ==
               @plaintext_opts ++ [headers: [{"authorization", "Bearer node-secret"}]]
    end

    test "connect options bound Mint's TCP connection establishment" do
      assert get_in(NodeAuth.connect_opts(), [:adapter_opts, :transport_opts, :timeout]) == 3_000
      assert NodeAuth.connect_timeout_ms() == 3_000
    end

    test "no credential and no port swap while the dial is off" do
      assert NodeAuth.tls_config() == nil
      refute Keyword.has_key?(NodeAuth.connect_opts(), :cred)
      assert NodeAuth.dial_address("10.42.3.34:9090") == "10.42.3.34:9090"
    end

    test "a malformed app-env value counts as off, never as a partial credential" do
      Application.put_env(:embervm, :noded_tls, %{spiffe_id: @noded_id})
      assert NodeAuth.tls_config() == nil
      refute Keyword.has_key?(NodeAuth.connect_opts(), :cred)
    end
  end

  describe "tls_config_from_env!/1" do
    test "off, unset, and non-boolean values all mean plaintext" do
      for value <- [nil, "", "false", "0", "no", " off "] do
        env = %{"EMBERVM_NODED_DIAL_TLS" => value}
        assert NodeAuth.tls_config_from_env!(&Map.get(env, &1)) == nil, inspect(value)
      end
    end

    test "on parses every value and trims whitespace" do
      env =
        full_env(%{"EMBERVM_NODED_DIAL_TLS" => " true\n", "EMBERVM_NODED_TLS_PORT" => " 9443 "})

      assert NodeAuth.tls_config_from_env!(&Map.get(env, &1)) == %{
               spiffe_id: @noded_id,
               tls_port: 9443,
               cert_file: "/run/embervm-svid/svid.pem",
               key_file: "/run/embervm-svid/svid_key.pem",
               bundle_file: "/run/embervm-svid/svid_bundle.pem"
             }
    end

    test "on with any missing value raises instead of falling back to plaintext" do
      for name <- [
            "EMBERVM_NODED_SPIFFE_ID",
            "EMBERVM_NODED_TLS_PORT",
            "EMBERVM_NODED_SVID_CERT",
            "EMBERVM_NODED_SVID_KEY",
            "EMBERVM_NODED_SVID_BUNDLE"
          ] do
        env = full_env(%{name => "  "})

        assert_raise ArgumentError, ~r/#{name} is required/, fn ->
          NodeAuth.tls_config_from_env!(&Map.get(env, &1))
        end
      end
    end

    test "on rejects a non-spiffe identity and a non-port" do
      env = full_env(%{"EMBERVM_NODED_SPIFFE_ID" => "embervm-noded"})

      assert_raise ArgumentError, ~r/must be a spiffe:\/\/ URI/, fn ->
        NodeAuth.tls_config_from_env!(&Map.get(env, &1))
      end

      for port <- ["0", "65536", "9443x", "tls"] do
        env = full_env(%{"EMBERVM_NODED_TLS_PORT" => port})

        assert_raise ArgumentError, ~r/must be a TCP port/, fn ->
          NodeAuth.tls_config_from_env!(&Map.get(env, &1))
        end
      end
    end
  end

  describe "connect_opts/0 with the SPIFFE dial on" do
    setup do
      Application.put_env(:embervm, :noded_tls, tls_config("/run/embervm-svid"))
      :ok
    end

    test "keeps the adapter timeout and the bearer header during the dual window" do
      Application.put_env(:embervm, :noded_bearer_token, "node-secret")
      opts = NodeAuth.connect_opts()

      assert get_in(opts, [:adapter_opts, :transport_opts, :timeout]) == 3_000
      assert opts[:headers] == [{"authorization", "Bearer node-secret"}]
      assert Keyword.keys(opts) == [:adapter_opts, :cred, :headers]
    end

    test "carries a GRPC.Credential built from file paths, verify_peer, and no SNI" do
      assert %GRPC.Credential{ssl: ssl} = NodeAuth.connect_opts()[:cred]

      assert ssl[:certfile] == ~c"/run/embervm-svid/svid.pem"
      assert ssl[:keyfile] == ~c"/run/embervm-svid/svid_key.pem"
      assert ssl[:cacertfile] == ~c"/run/embervm-svid/svid_bundle.pem"
      assert ssl[:verify] == :verify_peer
      assert ssl[:server_name_indication] == :disable
      assert {verify_fun, @noded_id} = ssl[:verify_fun]
      assert is_function(verify_fun, 3)
      assert is_function(ssl[:partial_chain], 1)
      assert ssl[:partial_chain].([<<1, 2, 3>>]) == :unknown_ca

      # Paths only: no PEM material anywhere in the dial options or app env.
      refute Keyword.has_key?(ssl, :cert)
      refute Keyword.has_key?(ssl, :key)
      refute Keyword.has_key?(ssl, :cacerts)
      refute inspect(Application.get_env(:embervm, :noded_tls)) =~ "BEGIN"
    end

    test "swaps the advertised plaintext port for the TLS port, host unchanged" do
      assert NodeAuth.dial_address("10.42.3.34:9090") == "10.42.3.34:9443"
      assert NodeAuth.dial_address("noded.embervm.svc:9090") == "noded.embervm.svc:9443"
      # Not a host:port pair: left alone rather than guessed at.
      assert NodeAuth.dial_address("unix:/run/noded.sock") == "unix:/run/noded.sock"
      assert NodeAuth.dial_address("[::1]:9090:extra") == "[::1]:9090:extra"
    end
  end

  describe "verify_peer_spiffe_id/3" do
    test "passes chain results and OTP failures through unchanged" do
      assert NodeAuth.verify_peer_spiffe_id(:cert, :valid, @noded_id) == {:valid, @noded_id}

      assert NodeAuth.verify_peer_spiffe_id(:cert, {:extension, :ext}, @noded_id) ==
               {:unknown, @noded_id}

      assert NodeAuth.verify_peer_spiffe_id(:cert, {:bad_cert, :cert_expired}, @noded_id) ==
               {:fail, {:bad_cert, :cert_expired}}
    end

    test "accepts exactly one URI SAN equal to the expected ID" do
      cert = decoded_peer_cert(@noded_id)
      assert NodeAuth.uri_sans(cert) == [@noded_id]
      assert NodeAuth.verify_peer_spiffe_id(cert, :valid_peer, @noded_id) == {:valid, @noded_id}
    end

    test "fails closed on a wrong, missing, or extra URI SAN" do
      wrong = decoded_peer_cert(@control_plane_id)

      assert NodeAuth.verify_peer_spiffe_id(wrong, :valid_peer, @noded_id) ==
               {:fail, {:bad_cert, {:spiffe_id_mismatch, [@control_plane_id]}}}

      # The same trust domain with a trailing path segment is a different workload.
      longer = decoded_peer_cert(@noded_id <> "/extra")

      assert {:fail, {:bad_cert, {:spiffe_id_mismatch, [_]}}} =
               NodeAuth.verify_peer_spiffe_id(longer, :valid_peer, @noded_id)

      none = decoded_peer_cert(nil)
      assert NodeAuth.uri_sans(none) == []

      assert NodeAuth.verify_peer_spiffe_id(none, :valid_peer, @noded_id) ==
               {:fail, {:bad_cert, {:spiffe_id_mismatch, []}}}

      two = decoded_peer_cert([@noded_id, @control_plane_id])

      assert {:fail, {:bad_cert, {:spiffe_id_mismatch, [_, _]}}} =
               NodeAuth.verify_peer_spiffe_id(two, :valid_peer, @noded_id)
    end
  end

  describe "handshake against a local mTLS listener" do
    @describetag :tmp_dir

    test "the right noded identity succeeds and the client presents its own SVID",
         %{tmp_dir: dir} do
      {config, server_opts} = write_chains(dir, @noded_id, @control_plane_id)
      {port, acceptor} = listen(server_opts)

      assert {:ok, socket} = :ssl.connect(~c"127.0.0.1", port, NodeAuth.ssl_opts(config), 2_000)
      assert_receive {:accepted, peer_ids}, 2_000
      assert peer_ids == [@control_plane_id]
      :ssl.close(socket)
      Task.shutdown(acceptor, :brutal_kill)
    end

    test "a wrong URI SAN fails closed even though the chain is trusted", %{tmp_dir: dir} do
      {config, server_opts} = write_chains(dir, @control_plane_id, @control_plane_id)
      {port, acceptor} = listen(server_opts)

      assert {:error, reason} =
               :ssl.connect(~c"127.0.0.1", port, NodeAuth.ssl_opts(config), 2_000)

      assert text(reason) =~ "spiffe_id_mismatch"
      Task.shutdown(acceptor, :brutal_kill)
    end

    test "an untrusted chain fails closed before the identity check", %{tmp_dir: dir} do
      {config, _} = write_chains(Path.join(dir, "cp"), @noded_id, @control_plane_id)
      {_, other_server} = write_chains(Path.join(dir, "other"), @noded_id, @control_plane_id)
      {port, acceptor} = listen(other_server)

      assert {:error, reason} =
               :ssl.connect(~c"127.0.0.1", port, NodeAuth.ssl_opts(config), 2_000)

      assert text(reason) =~ ~r/unknown_ca|bad_certificate/
      refute text(reason) =~ "spiffe_id_mismatch"
      Task.shutdown(acceptor, :brutal_kill)
    end

    test "a missing key file is a dial error, never a plaintext fallback", %{tmp_dir: dir} do
      {config, server_opts} = write_chains(dir, @noded_id, @control_plane_id)
      {port, acceptor} = listen(server_opts)
      File.rm!(config.key_file)

      assert {:error, reason} =
               :ssl.connect(~c"127.0.0.1", port, NodeAuth.ssl_opts(config), 2_000)

      assert text(reason) =~ "keyfile"
      Task.shutdown(acceptor, :brutal_kill)
    end

    test "a missing certificate file leaves the client without an identity and noded refuses it",
         %{tmp_dir: dir} do
      # OTP's client role tolerates an unreadable certfile by presenting no
      # certificate at all; noded's listener requires one, so the handshake
      # still fails closed on the server side rather than degrading.
      {config, server_opts} = write_chains(dir, @noded_id, @control_plane_id)
      {port, acceptor} = listen(server_opts)
      File.rm!(config.cert_file)

      # TLS 1.3 lets the client finish before the server's certificate_required
      # alert lands, so accept either an immediate error or a dead socket.
      case :ssl.connect(~c"127.0.0.1", port, NodeAuth.ssl_opts(config), 2_000) do
        {:error, _reason} -> :ok
        {:ok, socket} -> assert {:error, _} = :ssl.recv(socket, 0, 2_000)
      end

      refute_receive {:accepted, _}, 200
      Task.shutdown(acceptor, :brutal_kill)
    end

    test "rotated files are read by the next dial without a restart", %{tmp_dir: dir} do
      {config, _} = write_chains(Path.join(dir, "old"), @noded_id, @control_plane_id)
      {_, new_server} = write_chains(Path.join(dir, "new"), @noded_id, @control_plane_id)
      {port, acceptor} = listen(new_server)

      # The control plane's files still belong to the OLD trust root: refused.
      assert {:error, _} = :ssl.connect(~c"127.0.0.1", port, NodeAuth.ssl_opts(config), 2_000)

      # Rotate in place: the same PATHS now hold the NEW chain. OTP's PEM cache
      # keys on path and re-checks mtimes on its own timer; clearing it here
      # stands in for that timer so the test does not wait on it.
      for {from, to} <- [
            {Path.join(dir, "new/svid.pem"), config.cert_file},
            {Path.join(dir, "new/svid_key.pem"), config.key_file},
            {Path.join(dir, "new/svid_bundle.pem"), config.bundle_file}
          ] do
        File.chmod!(to, 0o644)
        File.cp!(from, to)
      end

      :ssl.clear_pem_cache()

      assert {:ok, socket} = :ssl.connect(~c"127.0.0.1", port, NodeAuth.ssl_opts(config), 2_000)
      :ssl.close(socket)
      Task.shutdown(acceptor, :brutal_kill)
    end
  end

  # -- helpers ----------------------------------------------------------------

  defp full_env(overrides) do
    Map.merge(
      %{
        "EMBERVM_NODED_DIAL_TLS" => "true",
        "EMBERVM_NODED_SPIFFE_ID" => @noded_id,
        "EMBERVM_NODED_TLS_PORT" => "9443",
        "EMBERVM_NODED_SVID_CERT" => "/run/embervm-svid/svid.pem",
        "EMBERVM_NODED_SVID_KEY" => "/run/embervm-svid/svid_key.pem",
        "EMBERVM_NODED_SVID_BUNDLE" => "/run/embervm-svid/svid_bundle.pem"
      },
      overrides
    )
  end

  defp tls_config(dir, spiffe_id \\ @noded_id) do
    %{
      spiffe_id: spiffe_id,
      tls_port: 9443,
      cert_file: Path.join(dir, "svid.pem"),
      key_file: Path.join(dir, "svid_key.pem"),
      bundle_file: Path.join(dir, "svid_bundle.pem")
    }
  end

  # A URI-SAN-only leaf, like an X.509-SVID: no DNS SAN. nil omits the
  # extension entirely; a list carries several URI entries.
  defp san_extension(nil), do: []

  defp san_extension(ids) do
    uris = for id <- List.wrap(ids), do: {:uniformResourceIdentifier, String.to_charlist(id)}
    [extensions: [{:Extension, {2, 5, 29, 17}, false, uris}]]
  end

  defp decoded_peer_cert(ids) do
    chain =
      :public_key.pkix_test_data(%{
        root: @key,
        intermediates: [],
        peer: @key ++ san_extension(ids)
      })

    :public_key.pkix_decode_cert(chain[:cert], :otp)
  end

  # A noded leaf and a control-plane leaf, each side's bundle trusting the
  # other's root (pkix_test_data issues one root per side; a real SPIRE trust
  # domain shares one). Writes the control plane's three files in the
  # spiffe-helper layout and returns the server's :ssl options in DER form.
  defp write_chains(dir, server_id, client_id) do
    File.mkdir_p!(dir)

    %{server_config: server, client_config: client} =
      :public_key.pkix_test_data(%{
        server_chain: %{root: @key, intermediates: [], peer: @key ++ san_extension(server_id)},
        client_chain: %{root: @key, intermediates: [], peer: @key ++ san_extension(client_id)}
      })

    config = tls_config(dir)
    File.write!(config.cert_file, pem(:Certificate, client[:cert]))
    File.write!(config.key_file, key_pem(client[:key]))
    File.write!(config.bundle_file, Enum.map_join(client[:cacerts], &pem(:Certificate, &1)))
    # 0444 / 0440 mirror spiffe-helper's cert_file_mode / key_file_mode.
    File.chmod!(config.cert_file, 0o444)
    File.chmod!(config.key_file, 0o440)

    server_opts = [
      cert: server[:cert],
      key: server[:key],
      cacerts: server[:cacerts],
      verify: :verify_peer,
      fail_if_no_peer_cert: true,
      reuseaddr: true,
      active: false
    ]

    {config, server_opts}
  end

  # Alert reasons carry Erlang-formatted charlists; render them whole.
  defp text(reason), do: inspect(reason, limit: :infinity, printable_limit: :infinity)

  defp pem(type, der), do: :public_key.pem_encode([{type, der, :not_encrypted}])
  defp key_pem({type, der}), do: :public_key.pem_encode([{type, der, :not_encrypted}])

  defp listen(server_opts) do
    parent = self()
    {:ok, listener} = :ssl.listen(0, server_opts)
    {:ok, {_, port}} = :ssl.sockname(listener)

    # Keeps accepting so one test can dial the same listener more than once
    # (a refused handshake followed by an accepted one). Killed by the test.
    acceptor = Task.async(fn -> accept_loop(listener, parent) end)
    {port, acceptor}
  end

  defp accept_loop(listener, parent) do
    with {:ok, transport} <- :ssl.transport_accept(listener, 5_000),
         {:ok, socket} <- :ssl.handshake(transport, 5_000),
         {:ok, peer_der} <- :ssl.peercert(socket) do
      peer = :public_key.pkix_decode_cert(peer_der, :otp)
      send(parent, {:accepted, NodeAuth.uri_sans(peer)})
      :ssl.close(socket)
    end

    accept_loop(listener, parent)
  end
end
