// Package statemachine contains the generated ModelCache state machine.
//
// All model_cache_*.go files are generated by sextant (projects/sextant)
// from modelcache.sextant.yaml in this directory. Do not edit them by hand —
// change the spec (or sextant's templates) and regenerate; the drift test in
// this package enforces this in CI.
//
//go:generate go run github.com/jomcgi/homelab/projects/sextant/cmd/sextant generate modelcache.sextant.yaml -o . --package statemachine --module github.com/jomcgi/homelab --api github.com/jomcgi/homelab/projects/operators/oci-model-cache/api/v1alpha1
package statemachine
