exports_files(
    [
        "application.yaml",
        "argocd-repo-cred.yaml",
        "kustomization.yaml",
    ],
    visibility = [
        "//bazel/helm:__pkg__",
        "//projects/loom/deploy:__pkg__",
    ],
)
