load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "vsockproto",
    srcs = ["proto.go"],
    importpath = "github.com/jomcgi/homelab/projects/firecracker/substrate/vsockproto",
    visibility = ["//visibility:public"],
)
