# Override BUILD for opentelemetry (installed by extension.bzl).
# Why an override: the Semgrep fork of imandra-ai/ocaml-opentelemetry is a
# git pin (lock url = the pinned commit's archive tarball, "opam": false),
# and its dune tree needs three things dune2bazel does not model: the
# Atomic compat module generated by a bundled gen.exe (always
# `include Stdlib.Atomic` + atomic.post412.mli on the pinned 5.3 sysroot,
# replicated as genrules), a (select ...) clause for the ambient-context
# hmap key, and the protobuf (rule) stanzas in src/proto (inert here: they
# are promote rules guarded by (enabled_if %{env:FORCE_GENPROTO=false}) and
# the generated sources are committed).
#
# Only the closure Semgrep's libs/telemetry needs is built: core,
# proto, atomic, client (Self_trace), the logs integration, and the
# ambient-context storage chain incl. its eio backend. The exporter clients
# (opentelemetry-client-ocurl: curl C bindings; opentelemetry-client-
# cohttp-eio: a full cohttp + TLS stack) are deliberately NOT built; the
# libs/telemetry Telemetry.ml overlay fails loudly where a backend would be
# created (see bazel/ocaml/semgrep_src/README.md). src/trace and src/lwt
# (depopts) are out of Semgrep's closure.
load("@homelab//bazel/ocaml:defs.bzl", "ocaml_library")

genrule(
    name = "atomic_ml",
    outs = ["atomic.ml"],
    cmd = "printf 'include Stdlib.Atomic' > $@",
)

genrule(
    name = "atomic_mli",
    srcs = ["src/atomic/atomic.post412.mli"],
    outs = ["atomic.mli"],
    cmd = "cp $< $@",
)

# findlib opentelemetry.atomic.
ocaml_library(
    name = "opentelemetry_atomic",
    srcs = [
        ":atomic_ml",
        ":atomic_mli",
    ],
    visibility = ["//visibility:public"],
    wrapped = True,
)

# findlib opentelemetry.ambient-context.types.
ocaml_library(
    name = "opentelemetry_ambient_context_types",
    srcs = glob([
        "src/ambient-context/types/*.ml",
        "src/ambient-context/types/*.mli",
    ]),
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = [
        "@ocaml_hmap//:hmap",
        "@ocaml_thread_local_storage//:thread_local_storage",
    ],
)

# The (select hmap_key_.ml from (-> hmap_key_.new.ml)) clause: a single
# unconditional arm, so the select is just a rename.
genrule(
    name = "hmap_key_ml",
    srcs = ["src/ambient-context/hmap_key_.new.ml"],
    outs = ["hmap_key_.ml"],
    cmd = "cp $< $@",
)

# findlib opentelemetry.ambient-context (the fork's own vendored copy;
# distinct from the ambient-context opam package, which Semgrep's
# Telemetry.ml also uses directly).
ocaml_library(
    name = "opentelemetry_ambient_context",
    srcs = [
        "src/ambient-context/opentelemetry_ambient_context.ml",
        "src/ambient-context/opentelemetry_ambient_context.mli",
        ":hmap_key_ml",
    ],
    opam_deps = ["threads"],
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = [
        ":opentelemetry_ambient_context_types",
        "@ocaml_thread_local_storage//:thread_local_storage",
    ],
)

# findlib opentelemetry.ambient-context.eio (fiber-local storage; what
# Semgrep's Telemetry.ml installs when running under eio).
ocaml_library(
    name = "opentelemetry_ambient_context_eio",
    srcs = glob([
        "src/ambient-context/eio/*.ml",
        "src/ambient-context/eio/*.mli",
    ]),
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = [
        ":opentelemetry_ambient_context",
        "@ocaml_eio//:eio",
        "@ocaml_hmap//:hmap",
        "@ocaml_thread_local_storage//:thread_local_storage",
    ],
)

# findlib opentelemetry.proto (committed ocaml-protoc output).
ocaml_library(
    name = "opentelemetry_proto",
    srcs = glob([
        "src/proto/*.ml",
        "src/proto/*.mli",
    ]),
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = ["@ocaml_pbrt//:pbrt"],
)

# findlib opentelemetry (core API).
ocaml_library(
    name = "opentelemetry",
    srcs = glob([
        "src/core/*.ml",
        "src/core/*.mli",
    ]),
    opam_deps = ["threads"],
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = [
        ":opentelemetry_ambient_context",
        ":opentelemetry_atomic",
        ":opentelemetry_proto",
        "@ocaml_hmap//:hmap",
        "@ocaml_pbrt//:pbrt",
        "@ocaml_ptime//:ptime",
        "@ocaml_ptime//:ptime_clock",
    ],
)

# findlib opentelemetry.client (shared exporter logic; Semgrep's
# Telemetry.ml calls Self_trace.set_enabled).
ocaml_library(
    name = "opentelemetry_client",
    srcs = glob([
        "src/client/*.ml",
        "src/client/*.mli",
    ]),
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = [
        ":opentelemetry",
        "@ocaml_mtime//:mtime",
        "@ocaml_mtime//:mtime_clock",
        "@ocaml_pbrt//:pbrt",
    ],
)

# findlib opentelemetry-logs (Logs reporter shipping otel log records).
ocaml_library(
    name = "opentelemetry_logs",
    srcs = glob([
        "src/integrations/logs/*.ml",
        "src/integrations/logs/*.mli",
    ]),
    visibility = ["//visibility:public"],
    wrapped = True,
    deps = [
        ":opentelemetry",
        "@ocaml_logs//:logs",
    ],
)
