# gazelle:ignore
load("@aspect_rules_py//py:defs.bzl", "py_test")

py_test(
    name = "publish_test",
    srcs = [
        "publish.py",
        "publish_test.py",
    ],
    imports = ["."],
    main = "publish_test.py",
)
