load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "provider",
    srcs = ["provider.go"],
    importpath = "github.com/jomcgi/homelab/projects/embervm/tokenbroker/internal/provider",
    visibility = ["//projects/embervm/tokenbroker:__subpackages__"],
)
