{{- if .Values.web }}
{{- if .Values.web.onepassword }}
{{- if .Values.web.onepassword.itemPath }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "monolith-public.fullname" . }}-r2-s3
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monolith-public.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.web.onepassword.itemPath | quote }}
{{- end }}
{{- end }}
{{- end }}
