-- Default-off agent coordination board (#5704).
--
-- Scope is enforced by the monolith-agents server before these rows are
-- touched. The agents_writer role can operate only this table, and UPDATE is
-- limited to the acknowledgement column. There is no DELETE grant.

CREATE TABLE knowledge.agent_board_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal TEXT NOT NULL,
    authenticated_subject TEXT NOT NULL,
    topic TEXT NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    acknowledged_by JSONB NOT NULL DEFAULT '[]'::jsonb,
    source_id TEXT UNIQUE,
    CONSTRAINT agent_board_topic_length_chk
        CHECK (char_length(topic) BETWEEN 1 AND 512),
    CONSTRAINT agent_board_body_length_chk
        CHECK (char_length(body) BETWEEN 1 AND 8000),
    CONSTRAINT agent_board_expiry_chk CHECK (expires_at > created_at),
    CONSTRAINT agent_board_ack_array_chk
        CHECK (jsonb_typeof(acknowledged_by) = 'array')
);

CREATE INDEX agent_board_topic_expiry_idx
    ON knowledge.agent_board_messages (topic, expires_at, created_at, id);

GRANT SELECT ON knowledge.agent_board_messages TO agents_writer;
GRANT INSERT (
    principal,
    authenticated_subject,
    topic,
    body,
    created_at,
    expires_at,
    acknowledged_by,
    source_id
) ON knowledge.agent_board_messages TO agents_writer;
GRANT UPDATE (acknowledged_by)
    ON knowledge.agent_board_messages TO agents_writer;
GRANT USAGE, SELECT
    ON SEQUENCE knowledge.agent_board_messages_id_seq TO agents_writer;
