-- Ids start at 100000 so that any bare number below it is unambiguously a
-- legacy GitHub issue number while both kinds appear in URLs and chat.
CREATE TABLE swarm.work_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    state TEXT NOT NULL,
    CONSTRAINT work_item_state_check CHECK (state IN ('open','ready','deferred','needs_human','active','done','closed')),
    close_reason TEXT,
    CONSTRAINT work_item_close_reason_check CHECK (close_reason IS NULL OR close_reason IN ('completed','not_planned','superseded','stale','github_closed')),
    CONSTRAINT work_item_close_reason_consistency_check CHECK ((state = 'closed') = (close_reason IS NOT NULL)),
    task_class TEXT,
    labels JSONB NOT NULL DEFAULT '[]'::jsonb,
    source_kind TEXT NOT NULL,
    CONSTRAINT work_item_source_kind_check CHECK (source_kind IN ('github','mcp','ui','discord','factory')),
    source_ref TEXT,
    trust TEXT NOT NULL,
    CONSTRAINT work_item_trust_check CHECK (trust IN ('trusted','semi_trusted','untrusted')),
    authority TEXT NOT NULL DEFAULT 'local',
    CONSTRAINT work_item_authority_check CHECK (authority IN ('github','local')),
    github_repo TEXT,
    github_issue_number INTEGER,
    CONSTRAINT work_item_github_key UNIQUE (github_repo, github_issue_number),
    CONSTRAINT work_item_github_both_check CHECK ((github_repo IS NULL) = (github_issue_number IS NULL)),
    CONSTRAINT work_item_github_number_check CHECK (github_issue_number IS NULL OR github_issue_number > 0),
    github_created_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at TIMESTAMPTZ
);

CREATE INDEX work_item_state_created_at_idx ON swarm.work_item (state, created_at);
CREATE INDEX work_item_authority_state_idx ON swarm.work_item (authority, state);

CREATE TABLE swarm.work_item_edge (
    id BIGSERIAL PRIMARY KEY,
    from_id BIGINT NOT NULL REFERENCES swarm.work_item (id),
    to_id BIGINT NOT NULL REFERENCES swarm.work_item (id),
    kind TEXT NOT NULL,
    CONSTRAINT work_item_edge_kind_check CHECK (kind IN ('blocks','parent','supersedes')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT work_item_edge_unique UNIQUE (from_id, to_id, kind),
    CONSTRAINT work_item_edge_self_check CHECK (from_id <> to_id)
);

CREATE INDEX work_item_edge_to_id_idx ON swarm.work_item_edge (to_id);

CREATE TABLE swarm.work_item_event (
    id BIGSERIAL PRIMARY KEY,
    work_item_id BIGINT NOT NULL REFERENCES swarm.work_item (id),
    version INTEGER NOT NULL,
    CONSTRAINT work_item_event_version_key UNIQUE (work_item_id, version),
    op TEXT NOT NULL,
    author_kind TEXT NOT NULL,
    author TEXT NOT NULL,
    change_json TEXT NOT NULL,
    cause_kind TEXT NOT NULL,
    cause_ref TEXT,
    stated_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE swarm.factory_receipt
  ADD COLUMN work_item_id BIGINT REFERENCES swarm.work_item (id);

CREATE INDEX factory_receipt_work_item_id_idx ON swarm.factory_receipt (work_item_id);
