"""Repo-markdown manifest loader for the docfix path allowlist.

This module loads the image-baked repo-markdown manifest
(knowledge/repo_docs_manifest.ndjson, generated by
//projects/monolith:gen_repo_docs_manifest). Its only live consumer is
knowledge/extraction.py:_allowed_doc_path, which uses the manifest as the
docfix path allowlist. The isolated repo-doc store this module once fed
(knowledge.repo_docs / knowledge.repo_doc_chunks) was dropped under #3905:
the reconcile job that populated it was removed in 66eb33979, so nothing
inserts a row anymore.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

# The manifest sits beside this module in the image runfiles (the :main binary's
# data). An env override exists purely for tests / ops.
_MANIFEST_NAME = "repo_docs_manifest.ndjson"


@dataclass(frozen=True)
class ManifestEntry:
    path: str
    sha256: str
    title: str
    content: str


def manifest_path() -> Path:
    override = os.environ.get("REPO_DOCS_MANIFEST_PATH")
    if override:
        return Path(override)
    return Path(__file__).resolve().parent / _MANIFEST_NAME


def load_manifest(path: Path | None = None) -> list[ManifestEntry]:
    p = path or manifest_path()
    if not p.exists():
        logger.warning("repo_docs: manifest not found at %s; nothing to index", p)
        return []
    entries: list[ManifestEntry] = []
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        o = json.loads(line)
        entries.append(
            ManifestEntry(
                path=o["path"],
                sha256=o["sha256"],
                title=o["title"],
                content=o["content"],
            )
        )
    return entries
