#!/usr/bin/env bash
# Auto-generate projects/home-cluster/kustomization.yaml with all deployable project paths
set -euo pipefail

cd "${BUILD_WORKSPACE_DIRECTORY:-$(git rev-parse --show-toplevel)}"

OUTPUT_FILE="projects/home-cluster/kustomization.yaml"

# Cluster roots and cluster-specific platform trees must never be enrolled in
# the home cluster. Keep these exclusions explicit even when a directory would
# currently be skipped by the discovery heuristics below.
EXCLUDED_ROOTS=(
	"projects/home-cluster"
	"projects/gke-cluster"
	"projects/platform-gke"
	"projects/gke-apps"
	# Decommissioned at home after the 2026-08-31 GKE cutover (the deploy dirs
	# stay: the hub's $values refs consume them). Inference stays enrolled until
	# the node-4 host-process move.
	"projects/embervm"
	"projects/monolith"
	"projects/monolith-public"
	"projects/mcp"
)

is_excluded() {
	local path="$1"
	for root in "${EXCLUDED_ROOTS[@]}"; do
		if [[ "$path" == "$root" || "$path" == "$root"/* ]]; then
			return 0
		fi
	done
	return 1
}

# Aggregator directories have their own top-level kustomization.yaml that
# includes their children. We include the aggregator itself, not the individual
# deploy/ dirs underneath it.
AGGREGATOR_DIRS=()
for dir in projects/*/kustomization.yaml; do
	parent=$(dirname "$dir")
	if is_excluded "$parent"; then
		continue
	fi
	# A directory is an aggregator if it contains subdirectories with their own
	# kustomization.yaml (either directly or under deploy/)
	has_children=false
	for child in "$parent"/*/kustomization.yaml "$parent"/*/deploy/kustomization.yaml; do
		if [ -f "$child" ]; then
			has_children=true
			break
		fi
	done
	if $has_children; then
		AGGREGATOR_DIRS+=("$parent")
	fi
done

is_under_aggregator() {
	local path="$1"
	for agg in "${AGGREGATOR_DIRS[@]}"; do
		if [[ "$path" == "$agg"/* ]]; then
			return 0
		fi
	done
	return 1
}

# Collect all paths to include in the root kustomization
PATHS=()

# 1. Add aggregator directories themselves
for agg in "${AGGREGATOR_DIRS[@]}"; do
	PATHS+=("$agg")
done

# 2. Find individual deploy/ kustomization.yaml files (1 and 2 levels deep)
#    Skip those under aggregator directories
for pattern in projects/*/deploy/kustomization.yaml projects/*/*/deploy/kustomization.yaml; do
	for f in $pattern; do
		[ -f "$f" ] || continue
		dir=$(dirname "$f")
		if ! is_excluded "$dir" && ! is_under_aggregator "$dir"; then
			PATHS+=("$dir")
		fi
	done
done

# Sort and deduplicate
IFS=$'\n' SORTED_PATHS=($(printf '%s\n' "${PATHS[@]}" | LC_ALL=C sort -u))
unset IFS

if [ ${#SORTED_PATHS[@]} -eq 0 ]; then
	echo "No deployable projects found"
	exit 0
fi

# Create output directory
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Generate kustomization.yaml
{
	cat <<'HEADER'
# AUTO-GENERATED by bazel/images/generate-home-cluster.sh — DO NOT EDIT
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
HEADER

	for p in "${SORTED_PATHS[@]}"; do
		# Convert to relative path from projects/home-cluster/
		echo "  - ../../$p"
	done
} >"$OUTPUT_FILE"
