apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://github.com/jomcgi-org/homelab.git
      targetRevision: HEAD
      path: projects/inference/deploy
      helm:
        releaseName: inference
        valueFiles:
          - $values/projects/inference/deploy/values.yaml
          - $values/projects/inference/deploy/values-gke.yaml
    - repoURL: https://github.com/jomcgi-org/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
