export const RUN_LEXICON = {
  stateWords: {
    queued: "queued",
    running: "running",
    reviewing: "reviewing",
    approved: "approved",
    changes_requested: "changes requested",
    review_cycles_exhausted: "cycles exhausted",
    escalated: "escalated",
    failed: "failed",
    cancelled: "cancelled",
    stranded: "stranded",
    blocked: "blocked",
  },
  nodeStates: {
    done: "done",
    running: "running",
    queued: "queued",
    future: "not started",
    escalated: "needs you",
    failed: "failed",
    cancelled: "not reached",
    refused: "refused",
    waiting: "waiting",
    passed: "passed",
    blocked: "blocked",
  },
  labels: {
    run: "run",
    attempt: "attempt",
    of: "of",
    turn: "turn",
    started: "started",
    updated: "updated",
    ago: "ago",
    engine: "engine",
    live: "live",
    asOf: "as of",
    staleShowing: "unreachable, showing",
    staleOld: "old state",
    absentNotice: "run shape unavailable: swarm engine offline",
    expandMembers: "expand run members",
    collapseMembers: "collapse run members",
    sessionsOnly: "sessions only",
    cancelRun: "cancel run",
    openBranch: "open branch",
    reviewedCommit: "reviewed commit",
    verdict: "verdict",
    queuedOn: "on the",
    queueWord: "queue",
    positionWord: "in line",
    whenTurnEnds: "when the turn ends",
    strandedBanner:
      "stranded by deploy: started on an older build, will not resume unaided",
    buildWord: "build",
    serverBuildWord: "server",
    attempts: "attempts",
    pushAttempts: "push attempts",
    retriesRemain: "retries remain",
    waitsOn: "waits on",
    needsYou: "needs you",
    masterEyebrow: "swarm runs",
    attention: "needs attention",
    nothingNeedsYou: "nothing needs you",
    noRuns: "no runs in flight",
    inFlight: "in flight",
    runsWord: "runs",
    runningWord: "running",
    waitingWord: "waiting",
    spend: "in-flight spend",
    allRuns: "runs",
    parallel: "in parallel",
    byWord: "by",
    evidence: "evidence",
    lastActivity: "last activity",
    stateConflict:
      "live activity disagrees with this state; treating it as unconfirmed",
    engineBelief: "engine belief",
    evidenceWord: "evidence",
    testimonyWord: "testimony",
    openSession: "open session",
    deviationWord: "deviation",
    approve: "approve",
    deny: "deny",
    blockedOnYou: "blocked on you",
    blockedUpstream: "blocked upstream",
    gateWord: "gate",
    budgetWord: "budget",
    session: "session",
    backToRun: "back to run",
    task: "task",
    selectRepo: "select a repo",
    budgetPositive: "budget must be greater than 0",
    runCreateFailed: "Run was not created",
    create: "create",
    createRun: "start run",
    creating: "creating…",
    startingRun: "starting…",
    deviations: "deviations",
    noSpendYet: "nothing spent yet",
    workflowWord: "workflow",
    copyId: "copy id",
    copied: "copied",
    // staleShowing trails off into an age ("unreachable, showing"), so it
    // cannot stand alone when the age was never measured.
    staleUnreachable: "unreachable",
    sessionsSection: "sessions",
    noneYet: "none yet",
    destroyConfirm: "Destroy this agent session?",
    cancelRunConfirm: "Cancel this swarm run?",
    pageTitle: "Agents",
    sessionsEyebrow: "agent sessions",
    searchLabel: "Search sessions",
    searchPlaceholder: "search transcripts",
    searchResults: "Search results",
    noMatchingTurns: "No matching turns",
    noRecentSessions: "No recent sessions",
    noSessionsYet: "No sessions yet",
    earlierRuns: "earlier",
    noEarlierRuns: "No earlier runs",
    showAll: "show all",
    showRecentOnly: "show recent only",
    destroy: "destroy",
    mobileBack: "← back",
    loadingSession: "Loading session…",
    loadingRun: "Loading run…",
    turnFailed: "failed",
    working: "working…",
    startingAgent: "starting the agent…",
    wakingVm: "waking vm…",
    startingUp: "starting up…",
    waitingForTurn: "waiting for the turn ahead…",
    sending: "sending…",
    send: "send",
    cancelWord: "cancel",
    defaultWord: "default",
    loadingRepos: "loading repos",
    scratchWorkspace: "none (scratch workspace)",
    loadingBranches: "loading branches",
    branchWord: "branch",
    modelWord: "model",
    repoWord: "repo",
    fullTask: "full task",
    launcherLabel: "start agent work",
    launcherHeading: "submit a task",
    launcherPromptPlaceholder: "what should the agent do?",
    submitTask: "submit task",
    taskCreateFailed: "Task was not created",
    classify: "classify",
    recentHeading: "recent",
    noRecentActivity: "no activity in the last 7 days",
    viewMoreInSidebar: "view more in sidebar",
    last7Days: "last 7 days",
    recentSessionsCount: "sessions",
    recentRunsCount: "runs",
    sessionsRegion: "Agent sessions",
    transcriptRegion: "Agent transcript",
    backToSessions: "Back to agent sessions",
    // Session walkthrough (ADR 056). Server-composed sentences (the payload
    // `message`, rationale quotes, truncation labels) are data, not lexicon;
    // these are the interface's own words only.
    walkSummary: "what changed",
    walkPointWord: "point",
    walkPointsWord: "points",
    walkFileWord: "file",
    walkFilesWord: "files",
    walkFileChanged: "file changed",
    walkFilesChanged: "files changed",
    walkProvenanceLead: "Agent-authored.",
    walkProvenanceBody:
      "These points are the implementer's account of its own change. The diff beside them is from git.",
    walkAccountLabel: "agent's account",
    walkUnexplainedMark: "!",
    walkContradictedMark: "×",
    walkUnexplainedTitle: "Unexplained change.",
    walkUnexplainedBody:
      "This file is in the diff, but the walkthrough never mentions it. It is surfaced rather than dropped.",
    walkContradictedTitle: "Contradicted path.",
    walkContradictedBody:
      "The agent named this file; the compare does not contain it.",
    walkMechanicalStep: "produced by tooling this turn",
    walkTouchedLabel: "files touched by tools this turn",
    walkDiffLoading: "loading diff…",
    walkDiffUnavailable: "diff unavailable",
    walkDiffsDesktop: "diffs read on a desktop",
    walkUnavailable: "walkthrough unavailable",
    walkRetry: "retry",
    walkLoading: "loading…",
  },
  punct: { dot: "·", arrow: "→", colon: ":" },
  deviationCodes: {
    retry_taken: "retry taken",
    budget_exceeded: "budget exceeded",
    attempts_exhausted: "attempts exhausted",
    model_mismatch: "model mismatch",
  },
  eventWords: {
    started: "started",
    completed: "completed",
    pushed: "pushed commit",
    gated: "passed gate",
    reviewed: "reviewed",
    canceled: "canceled by",
  },
  dispositionStates: {
    running: "running",
    approved: "approved",
    changes_requested: "changes requested, awaiting decision",
    escalated: "escalated, awaiting decision",
    cancelled: "cancelled",
    review_cycles_exhausted: "review cycles exhausted, awaiting decision",
    gated: "waiting at a gate",
  },
  verdictCodes: {
    approve: "approved",
    request_changes: "changes requested",
    blocked: "blocked",
    unparseable: "unable to parse",
  },
  units: { s: "s", m: "m", h: "h", d: "d" },
  ordinals: { 1: "1st", 2: "2nd", 3: "3rd", other: "th" },
};
