export const RUN_LEXICON = {
  stateWords: {
    queued: "queued",
    running: "running",
    reviewing: "reviewing",
    approved: "approved",
    changes_requested: "changes requested",
    escalated: "escalated",
    failed: "failed",
    cancelled: "cancelled",
    stranded: "stranded",
    blocked: "blocked",
  },
  nodeStates: {
    done: "done",
    running: "running",
    queued: "queued",
    future: "not started",
    escalated: "needs you",
    failed: "failed",
    cancelled: "not reached",
    refused: "refused",
    waiting: "waiting",
    passed: "passed",
    blocked: "blocked",
  },
  labels: {
    run: "run",
    attempt: "attempt",
    of: "of",
    turn: "turn",
    started: "started",
    updated: "updated",
    ago: "ago",
    engine: "engine",
    live: "live",
    asOf: "as of",
    staleShowing: "unreachable, showing",
    staleOld: "old state",
    absentNotice: "run shape unavailable: swarm engine offline",
    expandMembers: "expand run members",
    collapseMembers: "collapse run members",
    sessionsOnly: "sessions only",
    cancelRun: "cancel run",
    openBranch: "open branch",
    reviewedCommit: "reviewed commit",
    verdict: "verdict",
    queuedOn: "on the",
    queueWord: "queue",
    positionWord: "in line",
    whenTurnEnds: "when the turn ends",
    strandedBanner:
      "stranded by deploy: started on an older build, will not resume unaided",
    buildWord: "build",
    serverBuildWord: "server",
    attempts: "attempts",
    retriesRemain: "retries remain",
    waitsOn: "waits on",
    needsYou: "needs you",
    masterEyebrow: "swarm runs",
    attention: "needs attention",
    nothingNeedsYou: "nothing needs you",
    noRuns: "no runs in flight",
    inFlight: "in flight",
    runsWord: "runs",
    runningWord: "running",
    waitingWord: "waiting",
    spend: "in-flight spend",
    allRuns: "runs",
    parallel: "in parallel",
    byWord: "by",
    evidence: "evidence",
    deviationWord: "deviation",
    approve: "approve",
    deny: "deny",
    blockedOnYou: "blocked on you",
    blockedUpstream: "blocked upstream",
    gateWord: "gate",
    budgetWord: "budget",
    sessionMode: "session",
    runMode: "run",
    newSession: "new session",
    newRun: "new run",
    task: "task",
    mode: "mode",
    selectRepo: "select a repo",
    budgetPositive: "budget must be greater than 0",
    runCreateFailed: "Run was not created",
    create: "create",
    createRun: "start run",
    creating: "creating…",
    startingRun: "starting…",
  },
  punct: { dot: "·", arrow: "→", colon: ":" },
  units: { s: "s", m: "m", h: "h", d: "d" },
  ordinals: { 1: "1st", 2: "2nd", 3: "3rd", other: "th" },
};
