{{- if .Values.onepassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.onepassword.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.onepassword.itemPath | quote }}
{{- end }}
