filegroup(
    name = "deploy_values",
    srcs = ["values.yaml"],
    visibility = ["//projects/monolith-agents/chart:__pkg__"],
)

filegroup(
    name = "application",
    srcs = ["application.yaml"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "kustomization",
    srcs = ["kustomization.yaml"],
    visibility = ["//visibility:public"],
)
