load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "substrate",
    srcs = ["substrate.go"],
    importpath = "github.com/jomcgi/homelab/projects/embervm/noded/substrate",
    visibility = ["//projects/embervm/noded:__subpackages__"],
)
