filegroup(
    name = "renovate_migration_files",
    srcs = [
        "kustomization.yaml",
        "renovate/application.yaml",
        "renovate/kustomization.yaml",
    ],
    visibility = ["//projects/platform/renovate:__pkg__"],
)
