load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "vsockproto",
    srcs = ["proto.go"],
    importpath = "github.com/jomcgi/homelab/projects/embervm/noded/vsockproto",
    visibility = ["//projects/embervm/noded:__subpackages__"],
)
