{{- if and .Values.servingEnvoy.enabled .Values.servingEnvoy.edge.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "embervm.servingEdge.fullname" . }}
  labels:
    {{- include "embervm.servingEdge.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "embervm.servingEdge.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.servingEnvoy.listenerPort }}
      targetPort: http
{{- end }}
