apiVersion: v2
name: argocd
description: local argocd
type: application
version: 0.1.6
appVersion: "2.13.2"
dependencies:
  - name: argo-cd
    version: 8.6.4
    repository: https://argoproj.github.io/argo-helm
  - name: cf-ingress
    version: 0.1.0
    repository: "file://../cf-ingress-library"
annotations:
  org.opencontainers.image.source: "https://github.com/jomcgi/homelab"
  org.opencontainers.image.url: "https://github.com/jomcgi/homelab"
  org.opencontainers.image.licenses: "MPL-2.0"
